### ISSUE TITLE
cabal-gild discovers no extra-source-files

### ISSUE THREAD

**Issue by NorfairKing** [tfausak/cabal-gild#106]
I am using cabal-gild like this:

```
cabal-version: 1.12
-- This file has been generated from package.yaml by hpack version 0.36.0.
--
-- see: https://github.com/sol/hpack
name: site
version: 0.0.0
build-type: Simple
-- cabal-gild: discover assets content style templates
extra-source-files:
```

But no `extra-source-files` are being filled in.
Am I doing something silly?

**Comment by tfausak** [comment]
Which version of Gild are you using?

**Comment by NorfairKing** [comment]
```
$ cabal-gild --version
1.3.1.2
```
It's just what's in https://github.com/cachix/pre-commit-hooks.nix

**Comment by tfausak** [comment]
Using the discover pragma to discover `extra-source-files` was added in [version 1.3.4.0](https://github.com/tfausak/cabal-gild/releases/tag/1.3.4.0) via #86. However it's buggy until [version 1.5.0.1](https://github.com/tfausak/cabal-gild/releases/tag/1.5.0.1) because of #93 (which was fixed by #95). 

Can you try with the latest version to see what happens?

**Comment by NorfairKing** [comment]
@tfausak thanks for the response! Using a newer version would require an override that will be complex to maintain so I'll wait until the newer version is in the latest stable release that I use, which is in December.
Closing this until then.

**Comment by tfausak** [comment]
Ok, sounds good. Please do let me know if it doesn't work or behaves unexpectedly.
