### ISSUE TITLE
Option to place all field values on seperate line

### ISSUE THREAD

**Issue by recursion-ninja** [tfausak/cabal-gild#20]
I would very much like a configuration option to for each value of a `Field` within a "build-component"  to be placed on it's own line.

For purposes of discussion, call this hypothetical flag I am requesting `--line-break-components`. _A better name for the flag can be decided on later._

The following denote the start of a "build component" section within a `.cabal` file:
  -  `benchmark`
  -  `common`
  -  `executable`
  -  `library (name)`
  -  `test-suite`
  -  (I think there are just five, any others?)
 
Within these sections, if the `--line-break-components` is provided, I would like the disable the current functionality of placing the `Field` value on the same line as the `FieldName` if the value or value list is short enough to fit on one line. Instead, I would like the value (or values in the case of a list) to *always* be placed on a newline.

Let's use the  [`personal-website.cabal`](https://github.com/recursion-ninja/personal-website/blob/53fbdc981e391a50c856878d632bbc81f38fe42d/personal-website.cabal) file from my repository as a reference. Below is an example of the changed behavior the `--line-break-components` flags would produce. The top prefix of the `.cabal` file was omitted in the example below as the `--line-break-components` flag should not effect the "metadata" fields at the top of the cabal file.

 ## Current functionality

**Invocation:**
```
cabal-gild personal-website.cabal
```

**Output:**
```
<SNIP>

executable personal-website
  main-is:            SiteBuilder.hs
  build-depends:
    , base          >=4.16     && <5
    , binary        >=0.8.9.0
    , bytestring    >=0.11.4.0
    , cryptonite    >=0.30
    , filepath      >=1.4.2.2
    , hakyll        >=4.16.0.0
    , pandoc        >=3.0
    , pandoc-types  >=1.23
    , process       >=1.6.16.0
    , text          >=1.2.5.0
    , time          >=1.11.1.1

  default-extensions:
    DerivingStrategies
    LambdaCase
    NoGeneralizedNewtypeDeriving
    UnicodeSyntax
  default-language:   GHC2021
  ghc-options:
    -fdiagnostics-color=always -fhide-source-paths -fexcess-precision
    -fexpose-all-unfoldings -flate-specialise
    -fmax-simplifier-iterations=16 -foptimal-applicative-do
    -fspec-constr-count=8 -fspec-constr-keen -fspecialize-aggressively
    -fstatic-argument-transformation -Weverything
    -Wno-all-missed-specialisations -Wno-implicit-prelude
    -Wno-missing-import-lists -Wno-missing-safe-haskell-mode
    -Wno-monomorphism-restriction -Wno-type-defaults -Wno-unsafe

  -- Usability flags
  -- Optimization flags
  --
  -- Note: Do not use the '-threaded' GHC option!
  -- Threading can cause cache invalidation issues when building site
  -- Sanity check warnings
  --   1. Include all warnings by default
  --   2. Exclude the undesirable warnings
  if impl(ghc >=9.2)
    ghc-options: -Wno-missing-kind-signatures

  if impl(ghc >=9.4)
    ghc-options: -Wredundant-strictness-flags

  hs-source-dirs:     src

  if os(osx)
    ld-options: "-Wl,-no_fixup_chains"

  autogen-modules:    Paths_personal_website
  other-modules:
    AssetIncludes
    Compiler.AsciiDoc
    Compiler.BlogPostContext
    Compiler.Constants
    Compiler.EPUB
    Compiler.Generic
    Compiler.HTML
    Compiler.Markdown
    Compiler.PDF
    Compiler.Textual
    Compiler.Transformation.HeaderExclusion
    Compiler.Transformation.Table
    Indexer.Feed
    Indexer.HypertextAccess
    Indexer.Page
    Indexer.Robots
    Indexer.SiteMap
    PageBuilder.About
    PageBuilder.Blog
    PageBuilder.CV
    PageBuilder.Errors
    Paths_personal_website
```

 ## Requested functionality

**Invocation:**
```
cabal-gild --line-break-components personal-website.cabal
```

**Output:**
```
<SNIP>

executable personal-website
  main-is:
    SiteBuilder.hs

  build-depends:
    , base          >=4.16     && <5
    , binary        >=0.8.9.0
    , bytestring    >=0.11.4.0
    , cryptonite    >=0.30
    , filepath      >=1.4.2.2
    , hakyll        >=4.16.0.0
    , pandoc        >=3.0
    , pandoc-types  >=1.23
    , process       >=1.6.16.0
    , text          >=1.2.5.0
    , time          >=1.11.1.1

  default-extensions:
    DerivingStrategies
    LambdaCase
    NoGeneralizedNewtypeDeriving
    UnicodeSyntax

  default-language:
    GHC2021

  ghc-options:
    -fdiagnostics-color=always
    -fhide-source-paths
    -fexcess-precision
    -fexpose-all-unfoldings
    -flate-specialise
    -fmax-simplifier-iterations=16
    -foptimal-applicative-do
    -fspec-constr-count=8
    -fspec-constr-keen
    -fspecialize-aggressively
    -fstatic-argument-transformation 
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-implicit-prelude
    -Wno-missing-import-lists
    -Wno-missing-safe-haskell-mode
    -Wno-monomorphism-restriction
    -Wno-type-defaults
    -Wno-unsafe

  -- Usability flags
  -- Optimization flags
  --
  -- Note: Do not use the '-threaded' GHC option!
  -- Threading can cause cache invalidation issues when building site
  -- Sanity check warnings
  --   1. Include all warnings by default
  --   2. Exclude the undesirable warnings
  if impl(ghc >=9.2)
    ghc-options: -Wno-missing-kind-signatures

  if impl(ghc >=9.4)
    ghc-options: -Wredundant-strictness-flags

  hs-source-dirs:
    src

  if os(osx)
    ld-options: "-Wl,-no_fixup_chains"

  autogen-modules:
    Paths_personal_website

  other-modules:
    AssetIncludes
    Compiler.AsciiDoc
    Compiler.BlogPostContext
    Compiler.Constants
    Compiler.EPUB
    Compiler.Generic
    Compiler.HTML
    Compiler.Markdown
    Compiler.PDF
    Compiler.Textual
    Compiler.Transformation.HeaderExclusion
    Compiler.Transformation.Table
    Indexer.Feed
    Indexer.HypertextAccess
    Indexer.Page
    Indexer.Robots
    Indexer.SiteMap
    PageBuilder.About
    PageBuilder.Blog
    PageBuilder.CV
    PageBuilder.Errors
    Paths_personal_website
```

Would adding the `--line-break-components` optional flag be possible?

**Comment by tfausak** [comment]
I think the output you pasted is from `cabal-fmt`, not Gild. Gild doesn't align version constraints within `build-depends`, for example. Also Gild will always format a field on multiple lines if there are multiple values, like in `ghc-options`. It never does "paragraph fill" formatting. 

That aside, I see what you're asking for here. You want every field (within a component/section) to be formatted as a block rather than inline, even if that field only has one value. So for a smaller but hopefully representative example:

``` cabal
-- current
library
  default-language: GHC2021
```

``` cabal
-- requested
library
  default-language:
    GHC2021
```

I am unlikely to add a configuration option for this. Gild strives to be opinionated and unconfigurable (see [the goals section](https://github.com/tfausak/cabal-gild/blob/aadf4cbafd625c14900b732d7acdacf16aa2fba8/README.md#goals) of the README). 

That being said, I'm curious to know your motivation here. I have not personally encountered any package descriptions formatted this way. Why would you like them to be formatted like this? I'm particularly curious why you only want this formatting applied within a component and not at the top level. 

``` cabal
-- Why not this?
build-type:
  Simple
```

``` cabal
-- Or this?
library
  if impl(ghc >= 9.2)
    ghc-options:
      -Wno-missing-kind-signatures
```

**Comment by recursion-ninja** [comment]
> I think the output you pasted is from cabal-fmt, not Gild.

I accidentally got `cabal-gild-0.2.1.1` which explains the discrepancy between my observed output and the described output in your [announcement post](https://taylor.fausak.me/2024/02/17/gild/).

> You want every field (within a component/section) to be formatted as a block rather than inline, even if that field only has one value. 

Yes, that is probably the correct terminology for my request within the nomenclature of the `Cabal` library and "code formatting" domain.

> I'm particularly curious why you only want this formatting applied within a component and not at the top level.
> ```
> -- Why not this?
> build-type:
>   Simple
> ```

I find the top level definitions of a `.cabal` file are conceptually more like concise "plain text" narrative describing the package and that the top level definitions reads more easily _for me_ as a collection of paragraph-looking descriptions when rendered with "inline" mode.

However, I find the build-components sections are conceptually more like a nested specification of key-value pairs (some values being lists), and it is easier _for me_ to read that specification with consistent indentation and newlines which always correspond to the value's scoping with respect to its associated key.

After some reflection, I think the reason I conceptually read these sections of the `.cabal` files differently, is that the top level fields only contain a one-to-one key-value pair relationship with at most strictly single level of nesting depth, whereas the build component sections contain a one-to-many key-value pair relationship and have an arbitrarily depth of nesting. Hence, I find slightly different formatting between the top level definitions and the component sections better reflects their perceived  structural differences and improves their comprehension.

To address your other your given example:
> ```
> -- Or this?
> library
>   if impl(ghc >= 9.2)
>     ghc-options:
>       -Wno-missing-kind-signatures
> ```


I find this rendering as preferable, as each newline and indentation corresponds to the scoping of the value. 
 1. The `library` component has within it a list of sub-components, here it is a singleton list with a sole conditional component `if impl(ghc >= 9.2)`, each element in the list of the `library`'s sub-components is indented on a new line; here just the one conditional component. 
 2. The conditional component has a list of sub-components, here it is again a singleton list with a sole build field specification `ghc-options:`, so each element of this sub component list is further indented and on a new line. 
 3. Finally, the build field specification has a list of sub-components, here a singleton value `-Wno-missing-kind-signatures`, and each element of this sub component list is also indented and on a newline.

**Comment by tfausak** [comment]
I see, thanks for explaining! 

For what it's worth, the structure of package descriptions is extremely regular. There are only two things:

- Fields, which have a name and a value. They look like `name: value`. Some fields interpret their values as lists, but really it's just a bag of bytes. For example `default-extensions: CPP OverloadedStrings` looks like a list, but really it's just a string that is interpreted as a list by Cabal. It's similar to writing the JSON `{ "default-extensions": "CPP OverloadedStrings" }` (rather than `{ "default-extensions: [ "CPP", "OverloadedStrings" ] }`). 
- Sections, which have a name, optional arguments, and then nested fields and/or sections. They start with `section arg` and then contain anything nested within them. Notably `if` is actually a section rather than some kind of special thing.

I mention this because I think you may be interpreting package descriptions in a way that doesn't (quite) match the file format. Even at the top level there are simple fields like `name`, complex fields like `data-files`, and there are non-component sections like `flag`. 

My goal is to format things as regularly as possible. (Although now that I say that, I realize I haven't listed that as a goal. I'll fix that.) I want to avoid special-casing things as much as possible. And indeed there isn't really anything special about the `library` section (or `executable` or whatever else). They can all be formatted in the same way. 

I think we're essentially at an impasse here. I like how Gild formats things, and I don't want to add configuration. If you really want this format, I'd encourage creating a fork. The logic for laying things out on one line when possible is here:

https://github.com/tfausak/cabal-gild/blob/f596a7ef4e899c889d3f62d6dbbbcbd1d8c5f527/source/library/CabalGild/Action/Render.hs#L45-L51

**Comment by tfausak** [comment]
I see that you've made [cabal-gilding](https://github.com/recursion-ninja/cabal-gilding), so I'm going to close this.

**Comment by tfausak** [comment]
Would you mind taking a look at #54? I think it may allow Gild to produce output that you want without introducing configuration or special casing.
