### ISSUE TITLE
Formatting of exposed-modules and other-modules fields

### ISSUE THREAD

**Issue by nikita-volkov** [tfausak/cabal-gild#28]
Following is a snippet formatted using gild.

```cabal
...
library
  hs-source-dirs: library
  exposed-modules:
    Hasql.Pool
    Hasql.Pool.Observation

  other-modules: Hasql.Pool.Prelude
...
```

I see two problems with this:

- When it is decided to add another module to `other-modules` it will cause a messy diff which seems to violate the philosophy of the tool.
- It requires more editing on the user part to list another module.

I suggest to always use multiline formatting for the module lists, so that the snippet above would get formatted as follows:

```cabal
...
library
  hs-source-dirs: library
  exposed-modules:
    Hasql.Pool
    Hasql.Pool.Observation

  other-modules:
    Hasql.Pool.Prelude
...
```

**Comment by tfausak** [comment]
This was an intentional choice I made. Any field with a single item will be formatted on a single line. It does make for some unfortunate diffs when you go from 1 to 2+ items, but I felt that was a tradeoff worth making. 

I could special case `exposed-modules` and `other-modules`, but I'm not sure where it would end. What about `autogen-modules`? What about `build-depends`? And indeed, what about `hs-source-dirs`, which is a list of directories?

**Comment by tfausak** [comment]
It's worth noting that #20 is similar to this. That issue asks for each field to be formatted as a block. So what you're suggesting is kind of half way between what Gild does now and what that issue was asking for.

**Comment by nikita-volkov** [comment]
I understand the motivation to have a universal policy for all fields - it is simpler from the maintenance perspective and more predictable. However I suggest to look at it from a practical perspective, since Gild is essentially a productivity tool. With that in mind decisions can be made for each field in isolation by asking the question: which is more practical for this field.

The idea is: the practicality of the tool is a function of practicalities of each field in isolation. We can only strive towards maximizing the practicality but we can never reach it, so it makes sense to approach this incrementally by fine-tuning the tool on each step. Single field seems like a good enough unit of incrementation.

With that said, it seems that for fields which get modified most frequently and which tend to grow in the amount of constituents it seems that "multiline-always" mode is a more practical choice. `exposed-modules`, `other-modules`, `build-depends` seem to be clear candidates for this. `hs-source-dirs` OTOH is a good example of a field whose contents tend not to change in time, so it's not a candidate. Regarding `autogen-modules` I must say I've only learned about this field in this conversation, so I have no opinion :)

**Comment by tfausak** [comment]
For me, `other-modules` is almost always a single module: `Paths_whatever` (or `PackageInfo_whatever`). I would be annoyed to have that formatted on multiple lines. 

Our opposing viewpoints suggests a configuration option, but I'm opposed to adding those. 

You said that adding another modules requires more editing on the user's part. Could you explain that? The user can simply add the other module after the existing one using a space, then have Gild format it. I don't think it's any more difficult than adding another module when they're already on multiple lines. 

As for the diff being messier, yes that's true. Here's what a diff might look like:

``` diff
1c1,3
< exposed-modules: Example.One
---
> exposed-modules:
>   Example.One
>   Example.Two
```

This is bad because you lose track of who added `Example.One`. And obviously three lines change instead of only one. In my experience, these are acceptable tradeoffs for the consistency of formatting. It's not often that a list of modules goes from one to many (or many to one). 

If you really want the modules to be formatted as a block, you could put a comment in with them:

``` cabal
exposed-modules:
  -- multiple lines, please
  Example.One
```

**Comment by nikita-volkov** [comment]
> For me, other-modules is almost always a single module

My experience is definitely different :)

> Our opposing viewpoints suggests a configuration option, but I'm opposed to adding those.

I fully understand. It essentially makes Gild not just a tool, but also a standard. Adding even the tiniest tweaking option would break that.

> The user can simply add the other module after the existing one using a space, then have Gild format it.

Thanks, it's better. I didn't think about it. But still... :)

> If you really want the modules to be formatted as a block, you could put a comment in with them.

Seems like a workaround introducing its own set of problems. Doesn't seem to be worth the size of the problem. I don't think it will stick.

---

I really like that you clearly care about the git-friendliness. I just understood that I've opened this issue because I was implying that git-friendliness is one of the principles of this project and I could be misinterpreting. Any way it would definitely help to manage the expectations of users to have clearly stated principles. It will also give you a framework that will provide clear answers in such dilemmas and reduce arguments.

Close this at will.

**Comment by tfausak** [comment]
Diff friendliness is certainly important, but it's not the only consideration. If it was, everything would have to be formatted as a block. So I have to try to strike a balance between diff friendliness and everything else, including aesthetics and people's expectations. 

Cabal's syntax is a lot simpler than Haskell's, but I feel like this is similar to formatting import lists in Haskell. The most diff friendly way to do that is like this:

``` hs
import Data.List
  (
    sortWith,
  )
```

Or something similar, as long as each imported identifier is on its own line. There's certainly some merit to formatting things that way, but I think that in general people wouldn't like it. 

I'm happy with how Gild formats fields. If there's one element, the whole field goes on one line; otherwise each element goes on its own line. I think this strikes a good balance without caring about how the input is formatted, how long the lines are, or which field is being formatted. 

As such, I'm going to close this issue. You may be interested in [cabal-gilding](https://github.com/recursion-ninja/cabal-gilding), which sprung out of #20.

**Comment by tfausak** [comment]
Would you mind taking a look at #54? I think it may allow Gild to produce output that you want without introducing configuration or special casing.
