### ISSUE TITLE
`discover` pragma: Allow exclusion of modules

### ISSUE THREAD

**Issue by mmhat** [tfausak/cabal-gild#59]
The `expand` pragma of cabal-fmt allows the exclusion of certain modules: `-- cabal-fmt: expand directory/ -ModuleToExclude`.
It was nice if cabal-gild could do that too, since the `discover` pragma cannot be used if there are modules in the directory tree that should have mixed visibilities (`other-modules` vs `exposed-modules`). For example, if we have a directory tree similar to the following:
```
src/Foo/Bar.hs
src/Foo/Baz.hs
src/Foo/Helper.hs
```
Here, if `Foo.Helper` is supposed to be in `other-modules` while the other ones are supposed to be in `exposed-modules`, then we cannot use module discovery for `src`.

Also, the lack of this feature prevents module discovery to be used in test suites or executable components:
```
test-suite test
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs

  -- cabal-fmt: expand test/ -Main
  -- cabal-gild: discover test/
  other-modules:
```
Here, cabal-gild will add the `Main` module to the `other-modules` field. But this package description cannot be built by cabal:
```
    module ‘main:Main’ is defined in multiple files: test/Main.hs
                                                     test/Main.hs
```

**Comment by tfausak** [comment]
As a workaround, I'd suggest putting these source files in different directories.

**Comment by mmhat** [comment]
Hey @tfausak, thanks for the fast response.

> As a workaround, I'd suggest putting these source files in different directories.

Yes, that's a good workaround for some use cases, but I hope we agree that in general the module structure of a project should not be dictated by the code formatting tool used for the package description :smiley: 

I am working on a solution for this, but instead of replicating the UI of cabal-fmt I am exploring a more .gitignore-like interface:
`-- cabal-gild: discover src/ !src/*Test*`. For that I am using [System.FilePattern.Directory.getDirectoryFilesIgnore](https://hackage.haskell.org/package/filepattern-0.1.3/docs/System-FilePattern-Directory.html#v:getDirectoryFilesIgnore) under the hood. Not sure if that will result in a good user experience though; At this point it's really more of a experiment.

**Comment by tfausak** [comment]
See these related issues for context:

- https://github.com/phadej/cabal-fmt/issues/4
- https://github.com/tfausak/cabal-gild/pull/17
- https://github.com/tfausak/cabal-gild/pull/19

I considering adding some type of globbing to the discovery mechanism. Ultimately I decided to keep it simple for the time being. I thought it would be annoying to write something like `-- cabal-gild: discover src/**/*.{hs,lhs}` when most of the time `-- cabal-gild: discover src` would be sufficient. Adding in negations like `!src/**/*Test*` makes things even more complicated.

**Comment by tfausak** [comment]
I still think that putting source files in different directories is a reasonable workaround here. However I'm open to augmenting Gild's discover syntax to support this. The big question for me is what exactly this syntax should look like. Is it just `!x` or should it be more like the command line with `--exclude=x`? And what exactly does `x` represent: a directory, a file, a module, or something else? If it supports globbing, what kind of globbing (for example would `foo/*/bar` match `foo/a/b/bar` or would you need `foo/**/bar` for that)?

**Comment by konn** [comment]
Well, putting internal and exposed modules in different directories in small to medium projects.
But if one has a project with large number of modules and multiple `Internal` modules, things don't scale well. Consider the case where one has `My.Module.A` (located in `src/My/Module/A.hs`) in exposed directory and finally wanted to hide some internals and move them to `My.Module.A.Internal`. Then, one has to create new one in internal directory, say `src-internal/My/Module/A/Internal.hs`.

There are another situation: some parts of an internal module grows enough to be exported from some exposed module. If there is already corresponding exposed module, one can just copy-and-paste. But if there is no appropriate one, one has to create modules in exposed directory.

In both cases, one has to switch the location and create missing directories as needed. This requires some kinda context-switch and I think it is error-prone. I can also imagine the situation where one accidentally creates the "same" module.

So I think some kind of globbing feature helps to avoid such situations.
`.gitignore`-like syntax as proposed by @mmhat seems good and familiar, but as @tfausak pointed out, it is rather complicated and its semantics is not so clear.

I think just providing just an explicit limitation and exclusion mechanism would suffice, like:

```cabal
-- cabal-gild: discover src !**/Internal.hs !**/Internal/**.hs
exposed-modules:

-- cabal-gild: discover src **/Internal.hs **/Internal/**.hs
other-modules: 
```

or, CLI command-like syntax as @tfausak proposed:

```cabal
-- cabal-gild: discover src --exclude=**/Internal.hs --exclude=**/Internal/**.hs
exposed-modules: 

-- cabal-gild: discover src --include=**/Internal.hs --include=**/Internal/**.hs
other-modules: 
```

I'm in favour of the latter - although I think exclusion set feature is good enough, it is easily extendible with other features.
In any cases, the semantics is as:

1. List all the `*.{lhs,hs}`-files under `src`
2. If there is any `include` pattern, skip the modules which doesn't match any `include`s.
    - No include pattern is specified, this step does nothing and all the modules goes to step 3.
3. If one matches at least one of `exclude` pattern, skip it
4. Any module remaining in the list will go to the exposed list.

Note that step 2 is rather tricky - we have to treat "no-include" case separately. Otherwise, we have to specify `--include=**.hs` every time, which breaks the backwards compatibility.

As another example, a problem with tasty-discover can be accommodated as follows:

```cabal
test-suite tests
  type: exitcode-stdio-1.0
  hs-source-dirs: src
  main-is: Spec.hs
  -- cabal-gild: discover src --exclude=Spec.hs
  other-modules: 
```

As for globbing syntax, I think relying on existing implementation is good enough. I usually use [`Glob`](https://hackage.haskell.org/package/Glob-0.10.2/docs/System-FilePath-Glob.html) package, which has a clear semantics, but I think there also are many users of [`filepattern`](https://hackage.haskell.org/package/filepattern). It seems that `fil

**Comment by konn** [comment]
Ah, it seems that Cabal [itself provides a globbing functionality](https://hackage.haskell.org/package/Cabal-3.10.3.0/docs/Distribution-Simple-Glob.html). It might be good to use this one, as it ensures the detail of Glob pattern matches exactly with cabal's syntax.

**Comment by tfausak** [comment]
Cabal's globbing is idiosyncratic and not consistent across `cabal-version`s. The documentation covers the weirdness: https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-data-files

I think bash-style globstar would be fine, perhaps limited to `?`, `*`, and `**` (no `[...]` or `{...}`).
